Repository govau/design-system-site, pull requests merged in 2018-08, with the labels that each got.

#193 Added myself as a contributor
  content/components/_all.yml
  src/assets/img/contributors/raj-ghuman.jpg
Labels: documentation

#198 Remove 🌲 as it takes 11 seconds ⚰️
  .circleci/config.yml
Labels: enhancement

#200 Added correct html tags for text input documentation
  content/_data.yml
  content/components/text-inputs/block.md
  content/components/text-inputs/default.md
  content/components/text-inputs/textarea.md
Labels: documentation

#202 Update issue templates
  .github/ISSUE_TEMPLATE/----bug-report.md
  .github/ISSUE_TEMPLATE/---support-question.md
  .github/ISSUE_TEMPLATE/--join-the-community.md
  .github/ISSUE_TEMPLATE/-design-system-components.md
Labels: enhancement

#206 Update the bug report issue template
  .github/ISSUE_TEMPLATE/----bug-report.md
Labels: enhancement

#204 Fix discussion link
  .templates/new-module/discussion/github-intro.md
  content/components/accordion/discussion/github-intro.md
  content/components/animate/discussion/github-intro.md
  content/components/body/discussion/github-intro.md
  content/components/breadcrumbs/discussion/github-intro.md
  content/components/buttons/discussion/github-intro.md
  content/components/callout/discussion/github-intro.md
  content/components/control-input/discussion/github-intro.md
  content/components/core/discussion/github-intro.md
  content/components/cta-link/discussion/github-intro.md
  content/components/direction-links/discussion/github-intro.md
  content/components/footer/discussion/github-intro.md
  content/components/grid-12/discussion/github-intro.md
  content/components/header/discussion/github-intro.md
  content/components/headings/discussion/github-intro.md
  content/components/inpage-nav/discussion/github-intro.md
  content/components/keyword-list/discussion/github-intro.md
  content/components/link-list/discussion/github-intro.md
  content/components/page-alerts/discussion/github-intro.md
  content/components/progress-indicator/discussion/github-intro.md
  content/components/responsive-media/discussion/github-intro.md
  content/components/select/discussion/github-intro.md
  content/components/side-nav/discussion/github-intro.md
  content/components/skip-link/discussion/github-intro.md
  content/components/tags/discussion/github-intro.md
  content/components/text-inputs/discussion/github-intro.md
Labels: bug
