Repository govau/design-system-site, pull requests merged in 2018-09, with the labels that each got.

#210 hr tag aria-hidden rationale added
  content/components/body/rationale/horizontal-separator.md
  content/components/body/rationale/index.yml
  content/components/body/rationale/max-width.md
Labels: accessibility, enhancement

#209 Add display block for print styles
  src/sass/base/_structure.scss
Labels: enhancement

#217 Make footer use footerNav component
  content/_data.yml
  package-lock.json
  src/layout/structure/footer.js
Labels: enhancement

#219 Remove old issue template file add footer aria label
  ISSUE_TEMPLATE.md
  content/_data.yml
  package-lock.json
  src/layout/structure/footer.js
Labels: enhancement

#226 Update footer documentation, fix skip link bug [WIP]
  content/_data.yml
  content/components/_all.yml
  content/components/footer/rationale/browser-support.md
  content/components/footer/rationale/index.yml
  package-lock.json
  src/layout/structure/main-menu.js
Labels: bug, documentation

#228 Update footer docs, main nav, css source maps
  content/_data.yml
  content/components/_all.yml
  content/components/footer/rationale/browser-support.md
  content/components/footer/rationale/index.yml
  package-lock.json
  package.json
  src/assets/css/example.css.map
  src/assets/css/style.css.map
  src/layout/structure/main-menu.js
Labels: bug

#247 Update breadcrumbs rationale
  content/_data.yml
  content/components/_all.yml
  content/components/breadcrumbs/rationale/aria-current.md
  content/components/breadcrumbs/rationale/index.yml
Labels: documentation
