Repository govau/design-system-site, pull requests merged in 2018-07, with the labels that each got.

#164 Added sketch files for designers
  content/download/index.yml
  content/download/intro-designers-sidebar.md
  src/assets/css/style.css.map
  src/assets/img/sketch-logo.png
  src/assets/sketch/AuDS_components_v1.sketch.zip
  src/layout/download/intro-sidebar.js
  src/layout/download/intro.js
  src/sass/components/_download-intro.scss
  src/sass/components/_icons.scss
Labels: enhancement

#167 Fixes #163
  content/download/index.yml
  content/download/intro-designers-sidebar.md
  src/assets/css/style.css.map
  src/assets/img/sketch-logo.png
  src/assets/sketch/AuDS_components_v1.sketch.zip
  src/layout/download/intro-sidebar.js
  src/layout/download/intro.js
  src/sass/components/_download-intro.scss
  src/sass/components/_icons.scss
Labels: enhancement

#173 Highlight components with updated, new, or another string
  content/components/_all.yml
  src/layout/component/navigation-accordion.js
  src/layout/component/released.js
  src/sass/components/_badge.scss
  src/sass/components/_card--component.scss
Labels: enhancement

#176 Extended Markdown Table output
  src/markdown/renderer.js
Labels: bug

#178 Updated npm versions
  package-lock.json
Labels: bug

#177 Highlights for components, au-table around markdown tables, header focus lock
  content/components/_all.yml
  package-lock.json
  src/layout/component/navigation-accordion.js
  src/layout/component/released.js
  src/markdown/renderer.js
  src/sass/components/_badge.scss
  src/sass/components/_card--component.scss
Labels: bug, enhancement

#180 update number of projects on home page
  content/index/statisitics.md
Labels: documentation

#181 Stopped flickering on component code
  content/components/_all.yml
  src/assets/css/example.css.map
  src/assets/css/style.css.map
  src/js/footer/040-code-copy.js
  src/layout/code.js
  src/markdown/renderer.js
Labels: bug

#182 Stop flickering on page load with code boxes
  content/components/_all.yml
  content/index/statisitics.md
  src/assets/css/example.css.map
  src/assets/css/style.css.map
  src/js/footer/040-code-copy.js
  src/layout/code.js
  src/markdown/renderer.js
Labels: bug

#187 Header react code uses hero incorrectly in documentation
  content/components/header/default.md
  content/components/header/hero.md
Labels: bug, documentation

#191 Feature/replace class with classname on header component
  content/_data.yml
  content/components/header/default.md
  content/components/header/hero.md
Labels: bug

#192 Update side navigation docs to use correct semantic html ( nav -> aside )
  content/_data.yml
  content/components/side-nav/accessibility/code.md
  content/components/side-nav/default.md
  content/components/side-nav/examples/example-default/code.md
Labels: documentation
