Repository govau/design-system-site, pull requests merged in 2018-10, with the labels that each got.

#252 Update accordion docs
  content/_data.yml
  content/components/_all.yml
  content/components/accordion/accessibility/example-code.md
  content/components/accordion/accessibility/example-dark.md
  content/components/accordion/default.md
  content/components/accordion/examples/example-default/dark.md
  content/components/accordion/examples/example-default/example-code.md
  content/components/accordion/examples/example-default/example-dark.md
  content/components/accordion/examples/example-default/light.md
  content/components/accordion/examples/example-group/dark.md
  content/components/accordion/examples/example-group/example-code.md
  content/components/accordion/examples/example-group/example-dark.md
  content/components/accordion/examples/example-group/light.md
  content/components/accordion/group.md
  content/components/core/examples/example-spacing/example-code.md
  content/components/side-nav/accessibility/example-code.md
  content/components/side-nav/accessibility/example-dark.md
  content/components/side-nav/default.md
  content/components/side-nav/examples/example-default/example-code.md
  content/components/side-nav/examples/example-default/example-dark.md
  package-lock.json
  src/layout/component/navigation-accordion.js
  src/layout/structure/header-govau.js
Labels: bug, documentation

#254 Update footer col grid
  content/components/footer/examples/example-default/example-code.md
  content/components/footer/examples/example-default/example-dark.md
Labels: enhancement

#260 Update to Footer Affiliate link
  src/layout/structure/footer.js
Labels: enhancement

#264 Add breadcrumbs to getting started docs
  src/layout/breadcrumbs.js
  src/layout/getstarted/page.js
Labels: enhancement

#262 Sort functionality for side navigation, image added
  content/_data.yml
  content/community/intro.md
  content/get-started/content.md
  content/get-started/customise-color/index.yml
  content/get-started/customise-components/index.yml
  content/get-started/development-environment/index.yml
  content/get-started/sidenav.md
  src/assets/img/artwork-community-2.png
  src/layout/breadcrumbs.js
  src/layout/getstarted/page.js
  src/layout/side-nav.js
  src/sass/components/_basicpage.scss
Labels: enhancement

#267 Feature/add sass variables for core
  content/components/core/code/index.yml
  content/components/core/code/scss-functions.md
  content/components/core/code/scss-variables.md
  content/components/core/typography.md
Labels: documentation

#266 Getting started: create a component and design assets
  content/_data.yml
  content/components/core/code/index.yml
  content/components/core/code/scss-functions.md
  content/components/core/code/scss-variables.md
  content/components/core/typography.md
  content/get-started/content.md
  content/get-started/create-components/content.md
  content/get-started/create-components/index.yml
  content/get-started/design-assets/content.md
  content/get-started/design-assets/index.yml
  content/get-started/font-size-space/content.md
  content/get-started/sidenav.md
  src/assets/img/get-started/card-dark.png
  src/assets/img/get-started/card-title.png
  src/assets/img/get-started/card.png
  src/assets/img/get-started/replace-color-menu.png
  src/assets/img/get-started/replace-color-prompt.png
  src/assets/img/get-started/select-color.png
  src/assets/img/get-started/sketch-pages.png
  src/layout/breadcrumbs.js
Labels: article

#282 Fixing broken links on home and support page
  content/index/intro.md
  content/support/intro.md
Labels: bug

#286 Updated dependencies on yml file
  content/_data.yml
  content/components/_all.yml
  package-lock.json
Labels: enhancement

#285 Updated AU-footer to 3.0.1, amended docs
  content/_data.yml
  content/components/_all.yml
  content/components/control-input/radio.md
  content/components/footer/default.md
  content/components/footer/examples/example-default/example-code.md
  content/components/footer/examples/example-default/example-dark.md
  package-lock.json
  src/sass/components/_footer.scss
Labels: documentation

#294 Rename incorrect attribute accordion group
  content/_data.yml
  content/components/_all.yml
  content/components/accordion/group.md
  package-lock.json
Labels: documentation

#289 Add control input block example
  content/components/control-input/checkbox-block.md
  content/components/control-input/checkbox.md
  content/components/control-input/examples/example-checkbox-block/example-code.md
  content/components/control-input/examples/example-checkbox-block/example-dark.md
  content/components/control-input/examples/example-checkbox-block/index.yml
  content/components/control-input/examples/example-checkbox/example-code.md
  content/components/control-input/examples/example-checkbox/example-dark.md
  content/components/control-input/examples/example-checkbox/index.yml
  content/components/control-input/examples/example-radio-block/example-code.md
  content/components/control-input/examples/example-radio-block/example-dark.md
  content/components/control-input/examples/example-radio-block/index.yml
  content/components/control-input/index.yml
  content/components/control-input/radio-block.md
Labels: documentation
