Repository govau/design-system-site, pull requests merged in 2018-04, with the labels that each got.

#39 Feature/tagmanager test
  content/components/accordion/code/index.yml
  content/components/animate/code/index.yml
  content/components/breadcrumbs/code/index.yml
  content/components/buttons/code/index.yml
  content/components/callout/code/index.yml
  content/components/control-input/code/index.yml
  content/components/core/code/index.yml
  content/components/cta-link/code/index.yml
  content/components/direction-links/code/index.yml
  content/components/footer/code/index.yml
  content/components/header/code/index.yml
  content/components/headings/code/index.yml
  content/components/inpage-nav/code/index.yml
  content/components/keyword-list/code/index.yml
  content/components/link-list/code/index.yml
  content/components/page-alerts/code/index.yml
  content/components/progress-indicator/code/index.yml
  content/components/select/code/index.yml
  content/components/skip-link/code/index.yml
  content/components/text-inputs/code/index.yml
  src/js/footer/040-code-copy.js
  src/js/header/010-analytics.js
  src/layout/404.js
  src/layout/component/header.js
  src/layout/component/page.js
  src/layout/example/a11y.js
  src/layout/example/page.js
  src/layout/live/page.js
  src/layout/page.js
  src/sass/components/_component-header.scss
  src/sass/components/_component-status.scss
  src/sass/components/_sidebar.scss
Labels: blocked

#37 daily rebuild
  .circleci/config.yml
Labels: blocked

#88 Fix #83, #67, #90
  content/_data.yml
  src/helper/helper.js
  src/js/footer/030-mainmenu.js
  src/sass/components/_mainmenu.scss
Labels: enhancement

#91 Fix #80
  src/js/footer/010-helper.js
  src/js/footer/030-mainmenu.js
  src/layout/structure/header.js
Labels: accessibility, bug

#119 Google tag manager enhancements for dashboard
  src/js/footer/010-helper.js
  src/js/footer/040-code-copy.js
  src/js/footer/050-furnace-code.js
  src/layout/component/header.js
  src/layout/download/furnace.js
  src/sass/components/_component-header.scss
Labels: enhancement
