Repository govau/design-system-site, pull requests merged in 2018-11, with the labels that each got.

#314 fix broken link on component/heading page
  content/components/headings/default.md
  src/layout/component/page.js
Labels: documentation

#316 Updated animate docs
  content/_data.yml
  content/components/animate/rationale/nojquery.md
Labels: documentation

#318 Update animate docs
  content/_data.yml
  content/components/animate/rationale/nojquery.md
Labels: documentation

#317 Update main nav dependency and docs
  content/components/_all.yml
  content/components/main-nav/accessibility/example-code.md
  content/components/main-nav/accessibility/example-dark.md
  content/components/main-nav/accessibility/screenreader-desktop.md
  content/components/main-nav/accessibility/screenreader-mobile.md
  content/components/main-nav/default.md
  content/components/main-nav/examples/example-default/example-code.md
  content/components/main-nav/examples/example-default/example-dark.md
  content/components/main-nav/live/index.yml
  package-lock.json
Labels: documentation, enhancement

#324 Update control input docs & version
  content/_data.yml
  content/components/_all.yml
  content/components/control-input/checkbox-block.md
  content/components/control-input/checkbox.md
  content/components/control-input/radio-block.md
  content/components/control-input/radio.md
  package-lock.json
Labels: documentation

#325 Update control input docs
  content/_data.yml
  content/components/_all.yml
  content/components/control-input/checkbox-block.md
  content/components/control-input/checkbox.md
  content/components/control-input/radio-block.md
  content/components/control-input/radio.md
  package-lock.json
Labels: documentation

#326 Add missing 's' to customise components link
  content/get-started/create-components/content.md
Labels: bug

#329 Update dependencies
  content/_data.yml
  content/components/_all.yml
  package-lock.json
Labels: enhancement

#330 Update dependencies
  content/_data.yml
  content/components/_all.yml
  content/get-started/create-components/content.md
  package-lock.json
Labels: enhancement

#339 Update issue templates
  .github/ISSUE_TEMPLATE/---feature-request.md
Labels: enhancement

#340 add feature request template
  .github/ISSUE_TEMPLATE/---feature-request.md
Labels: enhancement

#341 fix broken link on get started page
  content/get-started/content.md
Labels: bug

#342 Add article on how we add space between components
  content/_data.yml
  content/get-started/content.md
  content/get-started/spacing-between-components/content.md
  content/get-started/spacing-between-components/index.yml
Labels: enhancement

#344 Replace <a> with <span> in side nav active item, fixed broken tabbing on a11y example
  content/_data.yml
  content/components/side-nav/accessibility/example-code.md
  content/components/side-nav/accessibility/example-dark.md
  content/components/side-nav/default.md
  content/components/side-nav/examples/example-default/example-code.md
  content/components/side-nav/examples/example-default/example-dark.md
Labels: documentation

#345 Replace <a> with <span> in side nav active item, fixed broken tabbing on a11y example
  content/_data.yml
  content/components/side-nav/accessibility/example-code.md
  content/components/side-nav/accessibility/example-dark.md
  content/components/side-nav/default.md
  content/components/side-nav/examples/example-default/example-code.md
  content/components/side-nav/examples/example-default/example-dark.md
Labels: documentation
