Repository govau/design-system-site, pull requests merged in 2019-04, with the labels that each got.

#499 Update starter docs, types for text inputs
  content/_data.yml
  content/components/_all.yml
  content/components/text-inputs/examples/example-width/example-code.md
  content/components/text-inputs/examples/example-width/example-dark.md
  content/components/text-inputs/width.md
  content/get-started/content.md
Labels: documentation, enhancement

#504 Fix console warning when building
  content/components/_all.yml
Labels: bug

#502 fix focus state around component sidebar links
  content/_data.yml
  src/sass/components/_navigation-accordion.scss
Labels: enhancement

#501 Fix core from being removed on npm download box
  src/js/footer/050-furnace-code.js
Labels: bug

#505 fix focus states, console warnings for unfound module, fix buggy select all button on download page
  content/_data.yml
  content/components/_all.yml
  src/js/footer/050-furnace-code.js
  src/sass/components/_navigation-accordion.scss
Labels: bug, enhancement

#509 Updating docs to reflect the word 'navigation' being removed from Main-Nav
  content/_data.yml
  content/components/_all.yml
  content/components/main-nav/accessibility/example-code.md
  content/components/main-nav/accessibility/example-dark.md
  content/components/main-nav/code/react-props.md
  content/components/main-nav/default.md
  content/components/main-nav/examples/example-default/example-code.md
  content/components/main-nav/examples/example-default/example-dark.md
Labels: documentation

#510 Remove word 'navigation' from footer
  content/components/footer/accessibility/example-code.md
  content/components/footer/accessibility/example-dark.md
  content/components/footer/code/react-props.md
  content/components/footer/default.md
  content/components/footer/examples/example-default/example-code.md
  content/components/footer/examples/example-default/example-dark.md
Labels: documentation

#512 Update AUheaderBrand description
  content/components/header/code/react-exports.md
Labels: documentation

#514 Add padding-top to fix 'Copy' button spacing on code exports
  src/sass/components/_code.scss
Labels: bug

#513 Correct named export for `header` component doc page
  content/components/header/code/react-exports.md
  src/sass/components/_code.scss
Labels: documentation

#521 Update support email to correct address
  content/support/email-the-team.md
  src/layout/component/footer.js
Labels: documentation
