Repository govau/design-system-site, pull requests merged in 2019-05, with the labels that each got.

#525 Add use case and rationale for AU-sronly class
  content/components/core/code/scss-functions.md
Labels: documentation

#534 workaround for markdown auto link conversion
  content/components/form/examples/example-field-errors/example-field-errors.md
Labels: documentation

#538 Renamed color -> colour for `Get started` docs
  content/get-started/content.md
  content/get-started/create-components/content.md
  content/get-started/customise-colour/content.md
  content/get-started/customise-colour/index.yml
  content/get-started/sidenav.md
  content/get-started/starter-kit/content.md
Labels: documentation

#540 Update spelling of colour, add links in roadmap
  content/get-started/content.md
  content/get-started/create-components/content.md
  content/get-started/customise-colour/content.md
  content/get-started/customise-colour/index.yml
  content/get-started/sidenav.md
  content/get-started/starter-kit/content.md
  content/roadmap/now.md
Labels: documentation

#541 Added Slack link in footer and community page
  content/_shared/footer.md
  content/community/intro.md
  content/index/intro.md
  content/support/intro.md
  src/layout/intro.js
  src/sass/components/_icons.scss
  src/sass/components/_intro.scss
Labels: documentation, good first issue

#543 Add design principles
  content/_shared/footer.md
  content/design-principles/index.yml
  content/design-principles/intro.md
  content/design-principles/principles.md
Labels: enhancement

#542 Added Slack link in community page and footer, add design principles
  content/_shared/footer.md
  content/community/intro.md
  content/design-principles/index.yml
  content/design-principles/intro.md
  content/design-principles/principles.md
  content/index/intro.md
  content/support/intro.md
  src/layout/intro.js
  src/sass/components/_icons.scss
  src/sass/components/_intro.scss
Labels: enhancement

#550 Implement keyboard accessible tabs
  src/js/footer/010-helper.js
  src/js/footer/070-tabs.js
  src/layout/component/code-demo.js
  src/sass/components/_tabs.scss
Labels: accessibility

#551 Implement keyboard accessible tabs
  content/_data.yml
  content/components/_all.yml
  src/js/footer/010-helper.js
  src/js/footer/070-tabs.js
  src/layout/component/code-demo.js
  src/sass/components/_tabs.scss
Labels: accessibility, enhancement

#552 Update striped table example to use correct HTML in doc example
  content/components/table/striped.md
Labels: enhancement

#555 Update community footer links, fix table in iframe not scrolling in IOS safari
  content/_data.yml
  content/community/footer-lists.md
  src/layout/component/code-demo.js
  src/sass/components/_table.scss
  src/sass/example.scss
Labels: enhancement

#561 Update tables to 0.1.2
  content/_data.yml
  content/components/_all.yml
  package-lock.json
Labels: enhancement

#562 Update tables to 0.1.2
  content/_data.yml
  content/components/_all.yml
  package-lock.json
Labels: enhancement

#560 Update tags for table component
  content/components/_all.yml
Labels: documentation

#559 Add au-label to fix labels with descenders obscured on:focus
  content/components/select/examples/example-block/example-code.md
  content/components/select/examples/example-block/example-dark.md
  content/components/text-inputs/accessibility/example-code.md
  content/components/text-inputs/accessibility/example-dark.md
  content/components/text-inputs/examples/example-block/example-code.md
  content/components/text-inputs/examples/example-block/example-dark.md
  content/components/text-inputs/examples/example-default/example-code.md
  content/components/text-inputs/examples/example-default/example-dark.md
  content/components/text-inputs/examples/example-disabled/example-code.md
  content/components/text-inputs/examples/example-disabled/example-dark.md
  content/components/text-inputs/examples/example-textarea/example-code.md
  content/components/text-inputs/examples/example-textarea/example-dark.md
  content/components/text-inputs/examples/example-valid-invalid/example-code.md
  content/components/text-inputs/examples/example-valid-invalid/example-dark.md
  content/components/text-inputs/examples/example-width/example-code.md
  content/components/text-inputs/examples/example-width/example-dark.md
Labels: enhancement

#563 Update table tags, add class `au-label` to text input and select labels
  content/components/_all.yml
  content/components/select/examples/example-block/example-code.md
  content/components/select/examples/example-block/example-dark.md
  content/components/text-inputs/accessibility/example-code.md
  content/components/text-inputs/accessibility/example-dark.md
  content/components/text-inputs/examples/example-block/example-code.md
  content/components/text-inputs/examples/example-block/example-dark.md
  content/components/text-inputs/examples/example-default/example-code.md
  content/components/text-inputs/examples/example-default/example-dark.md
  content/components/text-inputs/examples/example-disabled/example-code.md
  content/components/text-inputs/examples/example-disabled/example-dark.md
  content/components/text-inputs/examples/example-textarea/example-code.md
  content/components/text-inputs/examples/example-textarea/example-dark.md
  content/components/text-inputs/examples/example-valid-invalid/example-code.md
  content/components/text-inputs/examples/example-valid-invalid/example-dark.md
  content/components/text-inputs/examples/example-width/example-code.md
  content/components/text-inputs/examples/example-width/example-dark.md
Labels: enhancement

#558 Updated example
  content/components/body/examples/example-type/example-code.md
Labels: documentation
