Repository govau/design-system-site, pull requests merged in 2019-03, with the labels that each got.

#424 updating documentation for control inputs for version 3.0.0, bump dependencies
  content/_data.yml
  content/components/_all.yml
  content/components/control-input/accessibility/example-code.md
  content/components/control-input/accessibility/example-dark.md
  content/components/control-input/checkbox-block.md
  content/components/control-input/checkbox.md
  content/components/control-input/disabled.md
  content/components/control-input/examples/example-checkbox-block/example-code.md
  content/components/control-input/examples/example-checkbox-block/example-dark.md
  content/components/control-input/examples/example-checkbox/example-code.md
  content/components/control-input/examples/example-checkbox/example-dark.md
  content/components/control-input/examples/example-disabled/example-code.md
  content/components/control-input/examples/example-disabled/example-dark.md
  content/components/control-input/examples/example-radio-block/example-code.md
  content/components/control-input/examples/example-radio-block/example-dark.md
  content/components/control-input/examples/example-radio/example-code.md
  content/components/control-input/examples/example-radio/example-dark.md
  content/components/control-input/examples/example-small/example-code.md
  content/components/control-input/examples/example-small/example-dark.md
  content/components/control-input/examples/example-valid-invalid/example-code.md
  content/components/control-input/examples/example-valid-invalid/example-dark.md
  content/components/control-input/radio-block.md
  content/components/control-input/radio.md
  content/components/control-input/small.md
  content/components/control-input/valid-invalid.md
  package-lock.json
  src/layout/download/furnace.js
  src/sass/components/_fieldset.scss
Labels: documentation

#444 Bump dependencies, update select docs, update control input docs
  content/_data.yml
  content/components/_all.yml
  content/components/control-input/accessibility/example-code.md
  content/components/control-input/accessibility/example-dark.md
  content/components/control-input/checkbox-block.md
  content/components/control-input/checkbox.md
  content/components/control-input/disabled.md
  content/components/control-input/examples/example-checkbox-block/example-code.md
  content/components/control-input/examples/example-checkbox-block/example-dark.md
  content/components/control-input/examples/example-checkbox/example-code.md
  content/components/control-input/examples/example-checkbox/example-dark.md
  content/components/control-input/examples/example-disabled/example-code.md
  content/components/control-input/examples/example-disabled/example-dark.md
  content/components/control-input/examples/example-radio-block/example-code.md
  content/components/control-input/examples/example-radio-block/example-dark.md
  content/components/control-input/examples/example-radio/example-code.md
  content/components/control-input/examples/example-radio/example-dark.md
  content/components/control-input/examples/example-small/example-code.md
  content/components/control-input/examples/example-small/example-dark.md
  content/components/control-input/examples/example-valid-invalid/example-code.md
  content/components/control-input/examples/example-valid-invalid/example-dark.md
  content/components/control-input/radio-block.md
  content/components/control-input/radio.md
  content/components/control-input/small.md
  content/components/control-input/valid-invalid.md
  content/components/select/disabled.md
  content/components/select/examples/example-disabled/example-code.md
  content/components/select/examples/example-disabled/example-dark.md
  content/components/select/examples/example-disabled/index.yml
  content/components/select/examples/example-valid/example-code.md
  content/components/select/examples/example-valid/example-dark.md
  content/components/select/examples/example-valid/index.yml
  content/components/select/index.yml
  content/components/select/valid-invalid.md
  package-lock.json
  package.json
  src/layout/download/furnace.js
  src/sass/components/_fieldset.scss
Labels: documentation

#448 Use button instead of anchor for accordion
  src/layout/navigation-accordion.js
Labels: accessibility

#449 Use button instead of anchor for sidebar accordion
  src/layout/navigation-accordion.js
Labels: accessibility

#450 Update documentation for buttons as links
  content/components/buttons/link.md
Labels: documentation

#453 Update incorrect attribute for anchor tags in button docs
  content/components/buttons/link.md
Labels: documentation

#454 Updated template / homepage wording
  content/index/cards.md
  src/layout/templates/page.js
Labels: documentation

#455 Updated template / homepage wording
  content/index/cards.md
  src/layout/templates/page.js
Labels: documentation

#437 Add forms to in-progress table
  content/components/_all.yml
  content/components/form/default.md
  content/components/form/index.yml
Labels: documentation

#452 Added examples of different widths for text inputs
  content/_data.yml
  content/components/_all.yml
  content/components/buttons/examples/example-default/example-code.md
  content/components/text-inputs/code/react-props.md
  content/components/text-inputs/examples/example-width/example-code.md
  content/components/text-inputs/examples/example-width/example-dark.md
  content/components/text-inputs/examples/example-width/index.yml
  content/components/text-inputs/index.yml
  content/components/text-inputs/width.md
  package-lock.json
  src/sass/example.scss
Labels: documentation

#463 Update roadmap
  content/roadmap/later.md
Labels: documentation

#464 Update roadmap
  content/roadmap/later.md
Labels: documentation

#470 Update image links for contributor
  content/components/_all.yml
Labels: enhancement

#472 Hotfix - search button not taking up full width
  src/layout/search.js
Labels: bug

#477 Bumped package-lock.json
  content/_data.yml
  package-lock.json
Labels: maintenance

#485 fix markdown tables, wording for form component
  content/_data.yml
  content/components/_all.yml
  content/components/core/code/scss-functions.md
Labels: documentation

#469 fix for text and links colliding on download page
  src/layout/download/furnace.js
  src/sass/components/_furnace.scss
Labels: bug

#478 Bumped deps and 'pancake-sass', 'core', fix broken markdown tables on core page, links colliding on download page
  content/_data.yml
  content/components/_all.yml
  content/components/core/code/scss-functions.md
  package-lock.json
  src/layout/download/furnace.js
  src/sass/components/_furnace.scss
Labels: bug, maintenance

#486 Added a button to 'select all' of the component checkboxes on the download page
  content/_data.yml
  src/js/footer/050-furnace-code.js
  src/layout/download/furnace.js
  src/sass/components/_furnace.scss
Labels: enhancement

#489 Fix bug where select was not adding components to the npm copy list
  src/js/footer/050-furnace-code.js
Labels: bug

#488 Add select all components option on download page
  content/_data.yml
  src/js/footer/050-furnace-code.js
  src/layout/download/furnace.js
  src/sass/components/_furnace.scss
Labels: enhancement

#491 Resolved numerous broken markdown tables in #code component section
  content/_data.yml
  content/components/_all.yml
  content/components/accordion/code/react-props.md
  content/components/breadcrumbs/code/react-props.md
  content/components/buttons/code/react-props.md
  content/components/callout/code/react-props.md
  content/components/control-input/code/react-props.md
  content/components/cta-link/code/react-props.md
  content/components/direction-links/code/react-props.md
  content/components/footer/code/react-props.md
  content/components/grid-12/code/sass-usage.md
  content/components/header/code/react-props.md
  content/components/headings/code/react-props.md
  content/components/inpage-nav/code/react-props.md
  content/components/keyword-list/code/react-props.md
  content/components/link-list/code/react-props.md
  content/components/main-nav/code/react-props.md
  content/components/page-alerts/code/react-props.md
  content/components/progress-indicator/code/react-props.md
  content/components/select/code/react-props.md
  content/components/skip-link/code/react-props.md
  content/components/tags/code/react-props.md
  content/components/text-inputs/code/react-props.md
  content/get-started/customise-color/content.md
  content/get-started/customise-components/content.md
  content/get-started/npm-install/content.md
Labels: bug, documentation

#495 Host placeholder images locally
  content/components/footer/accessibility/example-code.md
  content/components/footer/accessibility/example-dark.md
  content/components/footer/default.md
  content/components/footer/examples/example-default/example-code.md
  content/components/footer/examples/example-default/example-dark.md
  content/components/header/code/react-usage.md
  content/components/header/default.md
  content/components/header/hero.md
  content/components/responsive-media/examples/example-default/example-code.md
  src/assets/img/placeholder/100X100.png
  src/assets/img/placeholder/157X80.png
  src/assets/img/placeholder/256X80.png
  src/assets/img/placeholder/320X320.png
  src/assets/img/placeholder/500X400.png
  src/assets/img/placeholder/600X260.png
  src/assets/img/placeholder/800X800.png
  src/layout/home/promo.js
  src/layout/intro.js
Labels: enhancement

#497 References for placehold.it images
  content/components/footer/accessibility/example-code.md
  content/components/footer/accessibility/example-dark.md
  content/components/footer/default.md
  content/components/footer/examples/example-default/example-code.md
  content/components/footer/examples/example-default/example-dark.md
  content/components/header/code/react-usage.md
  content/components/header/default.md
  content/components/header/hero.md
  content/components/responsive-media/examples/example-default/example-code.md
  src/assets/img/placeholder/100X100.png
  src/assets/img/placeholder/157X80.png
  src/assets/img/placeholder/256X80.png
  src/assets/img/placeholder/320X320.png
  src/assets/img/placeholder/500X400.png
  src/assets/img/placeholder/600X260.png
  src/assets/img/placeholder/800X800.png
  src/layout/home/promo.js
  src/layout/intro.js
Labels: documentation, enhancement
