Repository govau/design-system-site, pull requests merged in 2019-06, with the labels that each got.

#577 Update to metadata handling
  content/_data.yml
  content/roadmap/index.yml
  content/roadmap/intro.md
  content/roadmap/meta-data.md
  content/roadmap/next.md
  content/roadmap/now.md
  src/layout/description-list.js
Labels: documentation, enhancement

#529 Swap digital / dashboard imagery for acsc / sbr
  content/index/users.md
  src/assets/img/users-logo-acsc.png
  src/assets/img/users-logo-sbr.png
Labels: documentation

#579 Update roadmap, add acsc logo on home page
  content/_data.yml
  content/components/main-nav/code/react-props.md
  content/index/users.md
  content/roadmap/index.yml
  content/roadmap/intro.md
  content/roadmap/meta-data.md
  content/roadmap/next.md
  content/roadmap/now.md
  src/assets/img/users-logo-acsc.png
  src/assets/img/users-logo-sbr.png
  src/layout/description-list.js
Labels: documentation

#580 Add tips/rationale for templates
  content/_data.yml
  content/templates/content/index.yml
  content/templates/content/tips.md
  content/templates/form/index.yml
  content/templates/form/tips.md
  content/templates/home/index.yml
  content/templates/home/tips.md
Labels: documentation

#589 Update to statistics
  content/index/statisitics.md
Labels: documentation

#581 Add tips for structure/content/design for templates, bump fs stream, uppdate statistics
  content/_data.yml
  content/index/statisitics.md
  content/templates/content/index.yml
  content/templates/content/main.md
  content/templates/content/tips.md
  content/templates/form/index.yml
  content/templates/form/tips.md
  content/templates/home/index.yml
  content/templates/home/main.md
  content/templates/home/tips.md
  package-lock.json
Labels: documentation

#596 Add dhs logo to home page
  content/_data.yml
  content/index/users.md
  src/assets/img/users-logo-dhs.png
Labels: enhancement

#597 Resize dhs logo
  content/_data.yml
  src/assets/img/users-logo-dhs.png
Labels: enhancement

#600 Align table cell numbers right on a11y example
  content/_data.yml
  content/components/table/accessibility/example-code.md
Labels: enhancement

#604 Update direction link docs to reflect markup refactor
  content/components/direction-links/accessibility/example-code.md
  content/components/direction-links/accessibility/example-dark.md
  content/components/direction-links/accessibility/screenreader.md
  content/components/direction-links/buttons.md
  content/components/direction-links/default.md
  content/components/direction-links/examples/example-buttons/example-code.md
  content/components/direction-links/examples/example-buttons/example-dark.md
  content/components/direction-links/examples/example-default/example-code.md
  content/components/direction-links/examples/example-default/example-dark.md
  content/components/direction-links/rationale/index.yml
  content/components/direction-links/rationale/span.md
Labels: documentation, enhancement

#607 Add docs for cards
  content/components/_all.yml
  content/components/card/accessibility/a11y-colorblind/index.yml
  content/components/card/accessibility/a11y-grayscale/index.yml
  content/components/card/accessibility/a11y-keyboard/index.yml
  content/components/card/accessibility/colorblind.md
  content/components/card/accessibility/example-code.md
  content/components/card/accessibility/grayscale.md
  content/components/card/accessibility/index.yml
  content/components/card/accessibility/keyboard.md
  content/components/card/accessibility/screenreader.md
  content/components/card/card-image.md
  content/components/card/card-link.md
  content/components/card/card-list.md
  content/components/card/code/index.yml
  content/components/card/code/react-exports.md
  content/components/card/code/react-props.md
  content/components/card/code/react-usage.md
  content/components/card/default.md
  content/components/card/discussion/community-intro.md
  content/components/card/discussion/github-intro.md
  content/components/card/discussion/index.yml
  content/components/card/examples/example-default/example-code.md
  content/components/card/examples/example-default/index.yml
  content/components/card/examples/example-image/example-code.md
  content/components/card/examples/example-image/index.yml
  content/components/card/examples/example-link/example-code.md
  content/components/card/examples/example-link/index.yml
  content/components/card/examples/example-list/example-code.md
  content/components/card/examples/example-list/index.yml
  content/components/card/index.yml
  content/components/card/live/index.yml
  content/components/card/rationale/card-link.md
  content/components/card/rationale/index.yml
  content/components/cards/default.md
  content/components/released.md
  content/components/table/code/react-exports.md
  content/index/cards.md
  content/index/statisitics.md
  content/index/whats-in-our-system.md
  package-lock.json
  package.json
  src/assets/img/placeholder/256X80.png
  src/assets/img/placeholder/320X200.png
  src/assets/img/placeholder/320X320.png
  src/assets/img/placeholder/600X260.png
  src/assets/img/placeholder/800X800.png
  src/assets/svg/map.svg
  src/assets/svg/map.svg.card.png
  src/layout/card-list.js
  src/layout/card.js
  src/layout/component/released.js
  src/layout/home/features.js
  src/layout/home/promo.js
  src/sass/components/_card--component.scss
  src/sass/components/_card.scss
  src/sass/components/_features.scss
  src/sass/components/_promo.scss
  src/sass/components/_released-cards.scss
  src/sass/components/_table.scss
  src/sass/example.scss
Labels: documentation

#609 Add links to usage statistics cards
  content/_data.yml
  content/components/_all.yml
  content/index/statisitics.md
  package-lock.json
  src/layout/home/features.js
Labels: documentation

#611 Add links to usage statistics cards
  content/_data.yml
  content/components/_all.yml
  content/index/statisitics.md
  package-lock.json
  src/layout/home/features.js
Labels: enhancement

#612 Update placeholder image
  content/_data.yml
  content/components/card/accessibility/example-code.md
  content/components/card/card-link.md
  src/assets/img/placeholder/900X400.png
Labels: enhancement
