Repository govau/design-system-site, pull requests merged in 2019-07, with the labels that each got.

#613 Update docs to reflect table v0.2.0
  content/_data.yml
  content/components/_all.yml
  content/components/table/code/react-props.md
  content/components/table/default.md
  content/components/table/striped.md
  package-lock.json
Labels: documentation

#615 Change sketch download link to github repo
  content/download/intro-designers-sidebar.md
  src/layout/download/intro-sidebar.js
Labels: documentation

#606 update detail in page alert examples
  content/components/page-alerts/examples/example-default/example-code.md
  content/components/page-alerts/examples/example-default/example-dark.md
  content/components/page-alerts/examples/example-error/example-code.md
  content/components/page-alerts/examples/example-error/example-dark.md
  content/components/page-alerts/examples/example-success/example-code.md
  content/components/page-alerts/examples/example-success/example-dark.md
  content/components/page-alerts/examples/example-warning/example-code.md
  content/components/page-alerts/examples/example-warning/example-dark.md
Labels: documentation, enhancement

#621 Add nsw logo to front page
  content/index/users.md
  src/assets/img/users-logo-nsw.png
Labels: enhancement

#620 Update page alert example to provide more detail, NSW waratah logo
  content/_data.yml
  content/components/page-alerts/default.md
  content/components/page-alerts/error.md
  content/components/page-alerts/examples/example-default/example-code.md
  content/components/page-alerts/examples/example-default/example-dark.md
  content/components/page-alerts/examples/example-error/example-code.md
  content/components/page-alerts/examples/example-error/example-dark.md
  content/components/page-alerts/examples/example-success/example-code.md
  content/components/page-alerts/examples/example-success/example-dark.md
  content/components/page-alerts/examples/example-warning/example-code.md
  content/components/page-alerts/examples/example-warning/example-dark.md
  content/components/page-alerts/success.md
  content/components/page-alerts/warning.md
  content/index/users.md
  src/assets/img/users-logo-nsw.png
Labels: documentation

#617 Update cuttlebelle to fix security, update node-sass
  content/_data.yml
  content/components/_all.yml
  package-lock.json
  package.json
Labels: enhancement

#623 Update cuttlebelle, node-sass
  content/_data.yml
  content/components/_all.yml
  package-lock.json
  package.json
Labels: security

#627 Content and Home page overview pics out of date
  src/assets/img/templates/content.jpg
  src/assets/img/templates/content.png
  src/assets/img/templates/home.jpg
  src/assets/img/templates/home.png
Labels: enhancement

#628 aria-selected must be set to false on the unselected tabs
  src/js/footer/070-tabs.js
Labels: accessibility

#630 aria-selected must be set to false on the unselected tabs -> master
  src/js/footer/070-tabs.js
Labels: accessibility

#631 Live projects stats update
  content/index/statisitics.md
Labels: documentation

#632 Update home page stats dev --> master
  content/index/statisitics.md
Labels: enhancement

#633 update docs to reflect tag v4.0.0
  content/_data.yml
  content/components/_all.yml
  content/components/tags/accessibility/example-code.md
  content/components/tags/accessibility/example-dark.md
  content/components/tags/code/react-exports.md
  content/components/tags/code/react-props.md
  content/components/tags/code/react-usage.md
  content/components/tags/default.md
  content/components/tags/examples/example-default/example-code.md
  content/components/tags/examples/example-default/example-dark.md
  content/components/tags/examples/example-nolink/example-code.md
  content/components/tags/examples/example-nolink/example-dark.md
  content/components/tags/without-links.md
  package-lock.json
Labels: documentation, enhancement

#635 Update docs to reflect react number prop
  content/components/_all.yml
  content/components/text-inputs/code/react-props.md
  content/components/text-inputs/examples/example-width/example-code.md
  content/components/text-inputs/examples/example-width/example-dark.md
  package-lock.json
Labels: enhancement

#636 Add react number prop to text-inputs, card doc typo
  content/components/_all.yml
  content/components/card/examples/example-header/example-header.md
  content/components/card/header.md
  content/components/text-inputs/code/react-props.md
  content/index/users.md
  package-lock.json
Labels: documentation

#638 Update live site count
  content/index/statisitics.md
Labels: maintenance

#639 Update card to reflect v0.3.2 and live site count
  content/_data.yml
  content/components/_all.yml
  content/index/statisitics.md
  package-lock.json
Labels: documentation

#640 Update contributors for cards
  content/components/_all.yml
  src/assets/img/contributors/petr.jpg
Labels: documentation

#642 fix typo in cardlist html snippet
  content/components/card/card-list.md
Labels: documentation

#643 Update contributors on DS site
  content/components/_all.yml
  src/assets/img/contributors/kiri-hoy.jpg
Labels: enhancement
