Repository govau/design-system-site, pull requests merged in 2019-01, with the labels that each got.

#369 Customise templates: add copy button animation
  .gitignore
  src/assets/css/customise.css
  src/assets/css/customise.css.map
  src/assets/js/chameleon.js
  src/js/footer/010-helper.js
  src/layout/templates/customise.js
  src/sass/components/_icons.scss
  src/sass/customise.scss
Labels: enhancement

#370 Insert colours into customise form by default
  src/assets/js/chameleon.js
Labels: enhancement

#381 Update broken links to design system starter
  content/get-started/starter-kit/content.md
Labels: enhancement

#383 Fix chameleon url
  src/assets/js/chameleon.js
Labels: bug

#384 fix chameleon url
  src/assets/js/chameleon.js
Labels: bug

#385 Remove href in accordion docs
  content/components/accordion/accessibility/example-code.md
  content/components/accordion/accessibility/example-dark.md
  content/components/accordion/default.md
  content/components/accordion/examples/example-group/example-code.md
  content/components/accordion/examples/example-group/example-dark.md
  content/components/accordion/group.md
Labels: documentation

#386 Develop
  content/components/accordion/accessibility/example-code.md
  content/components/accordion/accessibility/example-dark.md
  content/components/accordion/default.md
  content/components/accordion/examples/example-group/example-code.md
  content/components/accordion/examples/example-group/example-dark.md
  content/components/accordion/group.md
Labels: accessibility

#403 Set NODE_ENV env var for deployments
  .deploy/manifest-prod.yml
  .deploy/manifest-staging.yml
  .deploy/manifest-testing.yml
Labels: bug, enhancement

#408 Remove `<abbr>` tag from au-body examples
  content/_data.yml
  content/components/body/accessibility/example-code.md
  content/components/body/accessibility/example-dark.md
  content/components/body/accessibility/screenreader.md
  content/components/body/examples/example-type/example-code.md
  content/components/body/examples/example-type/example-dark.md
  content/components/body/rationale/abbreviation.md
  content/components/body/rationale/index.yml
  content/components/body/type.md
Labels: accessibility

#406 Add small, valid, invalid, disabled examples control inputs
  content/components/accordion/examples/example-default/example-code.md
  content/components/accordion/examples/example-default/example-dark.md
  content/components/accordion/examples/example-group/example-code.md
  content/components/accordion/examples/example-group/example-dark.md
  content/components/control-input/disabled.md
  content/components/control-input/examples/example-disabled/example-code.md
  content/components/control-input/examples/example-disabled/example-dark.md
  content/components/control-input/examples/example-disabled/index.yml
  content/components/control-input/examples/example-small/example-code.md
  content/components/control-input/examples/example-small/example-dark.md
  content/components/control-input/examples/example-small/index.yml
  content/components/control-input/examples/example-valid-invalid/example-code.md
  content/components/control-input/examples/example-valid-invalid/example-dark.md
  content/components/control-input/examples/example-valid-invalid/index.yml
  content/components/control-input/index.yml
  content/components/control-input/small.md
  content/components/control-input/valid-invalid.md
Labels: documentation

#404 Add valid, invalid disabled text input examples
  content/components/text-inputs/disabled.md
  content/components/text-inputs/examples/example-disabled/example-code.md
  content/components/text-inputs/examples/example-disabled/example-dark.md
  content/components/text-inputs/examples/example-disabled/index.yml
  content/components/text-inputs/examples/example-valid-invalid/example-code.md
  content/components/text-inputs/examples/example-valid-invalid/example-dark.md
  content/components/text-inputs/examples/example-valid-invalid/index.yml
  content/components/text-inputs/index.yml
  content/components/text-inputs/valid-invalid.md
Labels: documentation

#410 Add examples for text inputs, control inputs, remove `abbr` in body example
  content/_data.yml
  content/components/accordion/examples/example-default/example-code.md
  content/components/accordion/examples/example-default/example-dark.md
  content/components/accordion/examples/example-group/example-code.md
  content/components/accordion/examples/example-group/example-dark.md
  content/components/body/accessibility/example-code.md
  content/components/body/accessibility/example-dark.md
  content/components/body/accessibility/screenreader.md
  content/components/body/examples/example-type/example-code.md
  content/components/body/examples/example-type/example-dark.md
  content/components/body/rationale/abbreviation.md
  content/components/body/rationale/index.yml
  content/components/body/type.md
  content/components/control-input/disabled.md
  content/components/control-input/examples/example-disabled/example-code.md
  content/components/control-input/examples/example-disabled/example-dark.md
  content/components/control-input/examples/example-disabled/index.yml
  content/components/control-input/examples/example-small/example-code.md
  content/components/control-input/examples/example-small/example-dark.md
  content/components/control-input/examples/example-small/index.yml
  content/components/control-input/examples/example-valid-invalid/example-code.md
  content/components/control-input/examples/example-valid-invalid/example-dark.md
  content/components/control-input/examples/example-valid-invalid/index.yml
  content/components/control-input/index.yml
  content/components/control-input/small.md
  content/components/control-input/valid-invalid.md
  content/components/text-inputs/disabled.md
  content/components/text-inputs/examples/example-disabled/example-code.md
  content/components/text-inputs/examples/example-disabled/example-dark.md
  content/components/text-inputs/examples/example-disabled/index.yml
  content/components/text-inputs/examples/example-valid-invalid/example-code.md
  content/components/text-inputs/examples/example-valid-invalid/example-dark.md
  content/components/text-inputs/examples/example-valid-invalid/index.yml
  content/components/text-inputs/index.yml
  content/components/text-inputs/valid-invalid.md
  src/sass/example.scss
Labels: accessibility, documentation

#411 Add aria invalid to invalid text inputs
  content/components/text-inputs/examples/example-valid-invalid/example-code.md
  content/components/text-inputs/examples/example-valid-invalid/example-dark.md
  content/components/text-inputs/valid-invalid.md
Labels: accessibility, documentation

#413 Apply selected colours to iFrame if query exists on page load
  src/assets/js/chameleon.js
Labels: bug

#414 Apply selected colours to iFrame if query exists on page load
  src/assets/js/chameleon.js
Labels: bug
